// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp73TazvuTkJxWrSPuCSSlA1cv6vqHgIw',
    appId: '1:197308298303:web:cbaaddece925bb291e748a',
    messagingSenderId: '197308298303',
    projectId: 'unite-445a',
    authDomain: 'unite-445a.firebaseapp.com',
    storageBucket: 'unite-445a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeWW2vGnqCL8_OjeyfoZCC5VdQt4Bqe8o',
    appId: '1:197308298303:android:4d855a9e85d77db61e748a',
    messagingSenderId: '197308298303',
    projectId: 'unite-445a',
    storageBucket: 'unite-445a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZcD5vtwiHfPSBYj2v76N4JkNpTvmPQeM',
    appId: '1:197308298303:ios:60b26a8218a940001e748a',
    messagingSenderId: '197308298303',
    projectId: 'unite-445a',
    storageBucket: 'unite-445a.appspot.com',
    androidClientId: '197308298303-vuq19kutu4umq3k917a2arm91d787fds.apps.googleusercontent.com',
    iosClientId: '197308298303-dk346r2rtg6hplhcao3ggvald7fcsf8p.apps.googleusercontent.com',
    iosBundleId: 'com.example.uniteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZcD5vtwiHfPSBYj2v76N4JkNpTvmPQeM',
    appId: '1:197308298303:ios:60b26a8218a940001e748a',
    messagingSenderId: '197308298303',
    projectId: 'unite-445a',
    storageBucket: 'unite-445a.appspot.com',
    androidClientId: '197308298303-vuq19kutu4umq3k917a2arm91d787fds.apps.googleusercontent.com',
    iosClientId: '197308298303-dk346r2rtg6hplhcao3ggvald7fcsf8p.apps.googleusercontent.com',
    iosBundleId: 'com.example.uniteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp73TazvuTkJxWrSPuCSSlA1cv6vqHgIw',
    appId: '1:197308298303:web:17099514f340cb051e748a',
    messagingSenderId: '197308298303',
    projectId: 'unite-445a',
    authDomain: 'unite-445a.firebaseapp.com',
    storageBucket: 'unite-445a.appspot.com',
  );

}